# -*- mode: ruby -*-
# vi: set ft=ruby :

$bash = <<BASH
  yum -y update
  yum -y install httpd php httpd-devel libxml2-devel mod_ssl
BASH

Vagrant.configure("2") do |config|
  config.vm.box = "boxcutter/ol72"
  config.vm.network "private_network", ip: "69.69.69.69"
  # HTTP
  config.vm.network "forwarded_port", guest: 80, host: 8080
  # HTTPS
  config.vm.network "forwarded_port", guest: 443, host: 5678
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end
  config.vm.provision "shell", inline: $bash
end
